### ISSUE TITLE
ErrNotFound not returned when FindOne doesn't find a record

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma-client-go#262]
I get a different error instead:

```
InterpretationError(\"Error for binding \\'0\\'\", Some(QueryGraphBuilderError(RecordNotFound(\"Record to update not found.\"))))", "errorVerbose": "Error occurred during query execution: InterpretationError(\"Error for binding \\'0\\'\", Some(QueryGraphBuilderError(RecordNotFound(\"Record to update not found.\"))))
```

**Comment by steebchen** [comment]
This is already fixed via #259, please update to `go get github.com/prisma/prisma-client-go@master` for now.

**Comment by Southclaws** [comment]
Ah, great, thanks! 😄

**Comment by Southclaws** [comment]
It seems this is still occurring on the latest commit:

![image](https://user-images.githubusercontent.com/1636971/95617706-c189b680-0a63-11eb-858f-8560d0fe1d92.png)

```
2020-10-09T19:22:03.299+0100	ERROR	worker/worker.go:25	failed to upsert server	{"error": "failed to update '{51.89.188.191:7777 <nil> {51.89.188.191:7777 BTTDM Zombie Survival (0.3.7) 42 100 Zombie Survival Survival false unknown} map[] <nil> <nil> true}': Error occurred during query execution:\nInterpretationError(\"Error for binding \\'0\\'\", Some(QueryGraphBuilderError(RecordNotFound(\"Record to update not found.\"))))", "errorVerbose": "Error occurred during query execution:\nInterpretationError(\"Error for binding \\'0\\'\", Some(QueryGraphBuilderError(RecordNotFound(\"Record to update not found.\"))))\nfailed to update '{51.89.188.191:7777 <nil> {51.89.188.191:7777 BTTDM Zombie Survival (0.3.7) 42 100 Zombie Survival Survival false unknown} map[] <nil> <nil> true}'\ngithub.com/openmultiplayer/server-index/server/src/serverdb.(*PrismaStorer).Upsert\n\tE:/Work/server-index/server/src/serverdb/prisma.go:72\ngithub.com/openmultiplayer/server-index/server/src/worker.(*Worker).RunWithSeed\n\tE:/Work/server-index/server/src/worker/worker.go:24\ngithub.com/openmultiplayer/server-index/server/src/app.(*App).Start.func3\n\tE:/Work/server-index/server/src/app/app.go:109\nruntime.goexit\n\tC:/Program Files/Go/src/runtime/asm_amd64.s:1373", "ip": "51.89.188.191:7777"}
```

**Comment by steebchen** [comment]
Did you re-generate the client?

**Comment by Southclaws** [comment]
No, completely forgot 😂
